% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{float}
\usepackage{tabularray}
\usepackage[normalem]{ulem}
\usepackage{graphicx}
\usepackage{rotating}
\UseTblrLibrary{siunitx}
\NewTableCommand{\tinytableDefineColor}[3]{\definecolor{#1}{#2}{#3}}
\newcommand{\tinytableTabularrayUnderline}[1]{\underline{#1}}
\newcommand{\tinytableTabularrayStrikeout}[1]{\sout{#1}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Visualization1},
  pdfauthor={Xihe},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Visualization1}
\author{Xihe}
\date{2026-04-01}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#Github URL: https://github.com/Xihe{-}Helena{-}Tang/HEB{-}126{-}Project.git }
\end{Highlighting}
\end{Shaded}

\subsection{R Markdown}\label{r-markdown}

This is an R Markdown document. Markdown is a simple formatting syntax
for authoring HTML, PDF, and MS Word documents. For more details on
using R Markdown see \url{http://rmarkdown.rstudio.com}.

When you click the \textbf{Knit} button a document will be generated
that includes both content as well as the output of any embedded R code
chunks within the document. You can embed an R code chunk like this:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'dplyr' was built under R version 4.5.2
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'ggplot2' was built under R version 4.5.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(sf)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'sf' was built under R version 4.5.2
\end{verbatim}

\begin{verbatim}
## Linking to GEOS 3.13.0, GDAL 3.8.5, PROJ 9.5.1; sf_use_s2() is TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(rnaturalearth)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'rnaturalearth' was built under R version 4.5.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(rnaturalearthdata)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'rnaturalearthdata'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:rnaturalearth':
## 
##     countries110
\end{verbatim}

\subsection{Including Plots}\label{including-plots}

You can also embed plots, for example:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{load}\NormalTok{(}\StringTok{"\textasciitilde{}/Documents/heb126/raw\_wvs7.rdata"}\NormalTok{)}
\FunctionTok{ls}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "WVS_Cross-National_Wave_7_v6_0"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wvs }\OtherTok{\textless{}{-}} \StringTok{\textasciigrave{}}\AttributeTok{WVS\_Cross{-}National\_Wave\_7\_v6\_0}\StringTok{\textasciigrave{}}
\end{Highlighting}
\end{Shaded}

Note that the \texttt{echo\ =\ FALSE} parameter was added to the code
chunk to prevent printing of the R code that generated the plot.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'lubridate' was built under R version 4.5.2
\end{verbatim}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v forcats   1.0.0     v stringr   1.6.0
## v lubridate 1.9.5     v tibble    3.3.0
## v purrr     1.1.0     v tidyr     1.3.1
## v readr     2.1.5     
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wvs }\SpecialCharTok{|\textgreater{}} \FunctionTok{count}\NormalTok{(Q21)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Q21     n
## 1  -5   145
## 2  -2   493
## 3  -1   668
## 4   1 20813
## 5   2 75101
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(sf)}
\FunctionTok{library}\NormalTok{(rnaturalearth)}
\FunctionTok{library}\NormalTok{(rnaturalearthdata)}

\CommentTok{\# 1. clean data}
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ wvs }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{select}\NormalTok{(}
    \AttributeTok{country =}\NormalTok{ B\_COUNTRY\_ALPHA,}
    \AttributeTok{imm =}\NormalTok{ Q21}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(country), imm }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{anti\_imm =} \FunctionTok{if\_else}\NormalTok{(imm }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\NormalTok{  )}

\CommentTok{\# 2. aggregate}
\NormalTok{country\_df }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(country) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{anti\_imm\_rate =} \FunctionTok{mean}\NormalTok{(anti\_imm),}
    \AttributeTok{n =} \FunctionTok{n}\NormalTok{(),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(n }\SpecialCharTok{\textgreater{}=} \DecValTok{50}\NormalTok{)}

\CommentTok{\# 3. map}
\NormalTok{world }\OtherTok{\textless{}{-}} \FunctionTok{ne\_countries}\NormalTok{(}\AttributeTok{scale =} \StringTok{"medium"}\NormalTok{, }\AttributeTok{returnclass =} \StringTok{"sf"}\NormalTok{)}

\NormalTok{map\_data }\OtherTok{\textless{}{-}}\NormalTok{ world }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{left\_join}\NormalTok{(country\_df, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"iso\_a3"} \OtherTok{=} \StringTok{"country"}\NormalTok{))}

\CommentTok{\# 4. plot}
\FunctionTok{ggplot}\NormalTok{(map\_data) }\SpecialCharTok{+}
  \FunctionTok{geom\_sf}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill =}\NormalTok{ anti\_imm\_rate)) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_viridis\_c}\NormalTok{(}
    \AttributeTok{option =} \StringTok{"plasma"}\NormalTok{,}
    \AttributeTok{labels =}\NormalTok{ scales}\SpecialCharTok{::}\NormalTok{percent,}
    \AttributeTok{na.value =} \StringTok{"grey90"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Anti{-}Immigrant Attitudes Across Countries (WVS Wave 7)"}\NormalTok{,}
    \AttributeTok{fill =} \StringTok{"Share rejecting immigrants"}\NormalTok{,}
    \AttributeTok{caption =} \StringTok{"Inglehart, R et al. 2022. World Values Survey: }
\StringTok{    Round Seven {-} Country{-}Pooled Datafile Version 5.0. }
\StringTok{    Madrid, Spain \& Vienna, Austria: JD Systems Institute \& WVSA Secretariat. }
\StringTok{    doi:10.14281/18241.24}
\StringTok{ }
\StringTok{"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Untitled_files/figure-latex/unnamed-chunk-5-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggsave}\NormalTok{(}
  \AttributeTok{filename =} \FunctionTok{paste0}\NormalTok{(}\StringTok{"Home/HEB126 Research/outcome/immigration\_map\_"}\NormalTok{, }\FunctionTok{Sys.Date}\NormalTok{(), }\StringTok{".png"}\NormalTok{),}
  \AttributeTok{width =} \DecValTok{10}\NormalTok{,}
  \AttributeTok{height =} \DecValTok{6}\NormalTok{,}
  \AttributeTok{dpi =} \DecValTok{300}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(haven)}
\FunctionTok{library}\NormalTok{(countrycode)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'countrycode' was built under R version 4.5.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(sf)}
\FunctionTok{library}\NormalTok{(rnaturalearth)}
\FunctionTok{library}\NormalTok{(rnaturalearthdata)}
\FunctionTok{library}\NormalTok{(ggplot2)}


\NormalTok{religion\_country }\OtherTok{\textless{}{-}}\NormalTok{ wvs }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{transmute}\NormalTok{(}
    \AttributeTok{country =}\NormalTok{ B\_COUNTRY\_ALPHA,   }\CommentTok{\# usually ISO alpha{-}3 country code}
    \AttributeTok{god\_importance =} \FunctionTok{as.numeric}\NormalTok{(Q164)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(god\_importance }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}  \CommentTok{\# removes {-}1, {-}2, {-}4, {-}5}
  \FunctionTok{group\_by}\NormalTok{(country) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{mean\_god\_importance =} \FunctionTok{mean}\NormalTok{(god\_importance, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{n =} \FunctionTok{n}\NormalTok{()}
\NormalTok{  )}

\NormalTok{world }\OtherTok{\textless{}{-}} \FunctionTok{ne\_countries}\NormalTok{(}\AttributeTok{scale =} \StringTok{"medium"}\NormalTok{, }\AttributeTok{returnclass =} \StringTok{"sf"}\NormalTok{)}

\NormalTok{map\_data }\OtherTok{\textless{}{-}}\NormalTok{ world }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{left\_join}\NormalTok{(religion\_country, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"iso\_a3"} \OtherTok{=} \StringTok{"country"}\NormalTok{))}

\FunctionTok{ggplot}\NormalTok{(map\_data) }\SpecialCharTok{+}
  \FunctionTok{geom\_sf}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill =}\NormalTok{ mean\_god\_importance), }\AttributeTok{color =} \StringTok{"white"}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{0.15}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_viridis\_c}\NormalTok{(}
    \AttributeTok{option =} \StringTok{"plasma"}\NormalTok{,}
    \AttributeTok{na.value =} \StringTok{"grey85"}\NormalTok{,}
    \AttributeTok{limits =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{10}\NormalTok{),}
    \AttributeTok{name =} \StringTok{"Importance of God}\SpecialCharTok{\textbackslash{}n}\StringTok{country mean"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Religiosity across countries"}\NormalTok{,}
    \AttributeTok{subtitle =} \StringTok{"World Values Survey Wave 7, Q164: Importance of God, 1–10 scale"}\NormalTok{,}
    \AttributeTok{caption =} \StringTok{"Negative WVS missing codes removed: Don\textquotesingle{}t know, No answer, Not asked, Missing"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Untitled_files/figure-latex/unnamed-chunk-6-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggsave}\NormalTok{(}\StringTok{"religion\_map.png"}\NormalTok{, }\AttributeTok{width =} \DecValTok{10}\NormalTok{, }\AttributeTok{height =} \DecValTok{6}\NormalTok{, }\AttributeTok{dpi =} \DecValTok{300}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{country\_combined }\OtherTok{\textless{}{-}}\NormalTok{ religion\_country }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{inner\_join}\NormalTok{(country\_df, }\AttributeTok{by =} \StringTok{"country"}\NormalTok{)}

\FunctionTok{ggplot}\NormalTok{(country\_combined, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ mean\_god\_importance, }\AttributeTok{y =}\NormalTok{ anti\_imm\_rate)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{size =} \DecValTok{2}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{x =} \StringTok{"Mean importance of God"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Share rejecting immigrants"}\NormalTok{,}
    \AttributeTok{title =} \StringTok{"Religiosity and Anti{-}Immigrant Attitudes"}\NormalTok{,}
    \AttributeTok{subtitle =} \StringTok{"WVS Wave 7 country{-}level relationship"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Untitled_files/figure-latex/unnamed-chunk-7-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggsave}\NormalTok{(}\StringTok{"religiosity\_scatter.png"}\NormalTok{, }\AttributeTok{width =} \DecValTok{10}\NormalTok{, }\AttributeTok{height =} \DecValTok{6}\NormalTok{, }\AttributeTok{dpi =} \DecValTok{300}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{religion\_identity\_country }\OtherTok{\textless{}{-}}\NormalTok{ wvs }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{transmute}\NormalTok{(}
    \AttributeTok{country =}\NormalTok{ B\_COUNTRY\_ALPHA,}
    \AttributeTok{religious\_identity =} \FunctionTok{as.numeric}\NormalTok{(Q170)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(religious\_identity }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(country) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{share\_religious =} \FunctionTok{mean}\NormalTok{(religious\_identity }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{share\_not\_religious =} \FunctionTok{mean}\NormalTok{(religious\_identity }\SpecialCharTok{==} \DecValTok{2}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{share\_atheist =} \FunctionTok{mean}\NormalTok{(religious\_identity }\SpecialCharTok{==} \DecValTok{3}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{n =} \FunctionTok{n}\NormalTok{(),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(n }\SpecialCharTok{\textgreater{}=} \DecValTok{50}\NormalTok{)}


\NormalTok{country\_combined\_q173 }\OtherTok{\textless{}{-}}\NormalTok{ country\_df }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{inner\_join}\NormalTok{(religion\_identity\_country, }\AttributeTok{by =} \StringTok{"country"}\NormalTok{)}


\FunctionTok{ggplot}\NormalTok{(country\_combined\_q173, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ share\_religious, }\AttributeTok{y =}\NormalTok{ anti\_imm\_rate)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{size =} \DecValTok{2}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ scales}\SpecialCharTok{::}\NormalTok{percent) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ scales}\SpecialCharTok{::}\NormalTok{percent) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{x =} \StringTok{"The only acceptable religion is mine"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Share rejecting immigrants"}\NormalTok{,}
    \AttributeTok{title =} \StringTok{"Religious Exclusioin and Anti{-}Immigrant Attitudes"}\NormalTok{,}
    \AttributeTok{subtitle =} \StringTok{"WVS Wave 7, country{-}level relationship"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Untitled_files/figure-latex/unnamed-chunk-8-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggsave}\NormalTok{(}\StringTok{"exclusion\_scatter.png"}\NormalTok{, }\AttributeTok{width =} \DecValTok{10}\NormalTok{, }\AttributeTok{height =} \DecValTok{6}\NormalTok{, }\AttributeTok{dpi =} \DecValTok{300}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wvs }\OtherTok{\textless{}{-}}\NormalTok{ wvs }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{exclusivism =} \FunctionTok{case\_when}\NormalTok{(}
\NormalTok{      Q170 }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{) }\SpecialCharTok{\textasciitilde{}} \DecValTok{1}\NormalTok{,   }\CommentTok{\# agree}
\NormalTok{      Q170 }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{) }\SpecialCharTok{\textasciitilde{}} \DecValTok{0}\NormalTok{,   }\CommentTok{\# disagree}
      \ConstantTok{TRUE} \SpecialCharTok{\textasciitilde{}} \ConstantTok{NA\_real\_}
\NormalTok{    )}
\NormalTok{  )}

\NormalTok{country\_religion\_exclusion }\OtherTok{\textless{}{-}}\NormalTok{ wvs }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(}\AttributeTok{country =}\NormalTok{ B\_COUNTRY\_ALPHA) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}
   
    \AttributeTok{exclusivism\_rate =} \FunctionTok{mean}\NormalTok{(exclusivism, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{n =} \FunctionTok{n}\NormalTok{(),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(n }\SpecialCharTok{\textgreater{}=} \DecValTok{50}\NormalTok{)}

\NormalTok{country\_combined }\OtherTok{\textless{}{-}}\NormalTok{ country\_df }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{inner\_join}\NormalTok{(country\_religion\_exclusion, }\AttributeTok{by =} \StringTok{"country"}\NormalTok{)}

\FunctionTok{lm}\NormalTok{(anti\_imm\_rate }\SpecialCharTok{\textasciitilde{}}\NormalTok{ exclusivism\_rate, }\AttributeTok{data =}\NormalTok{ country\_combined)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = anti_imm_rate ~ exclusivism_rate, data = country_combined)
## 
## Coefficients:
##      (Intercept)  exclusivism_rate  
##           0.1223            0.2227
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(haven)}
\FunctionTok{library}\NormalTok{(dplyr)}

\CommentTok{\# 1. Load witchcraft dataset}
\NormalTok{witch }\OtherTok{\textless{}{-}} \FunctionTok{read\_dta}\NormalTok{(}\StringTok{"\textasciitilde{}/Downloads/dataverse\_files/plos\_data\_country.dta"}\NormalTok{)}

\CommentTok{\# 2. Clean it (keep only what you need)}
\NormalTok{witch\_clean }\OtherTok{\textless{}{-}}\NormalTok{ witch }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{transmute}\NormalTok{(}
    \AttributeTok{country =}\NormalTok{ isocode,}
    \AttributeTok{witchcraft\_rate =}\NormalTok{ witchcraft}
\NormalTok{  )}

\CommentTok{\# 3. Merge with your existing dataset}
\CommentTok{\# (assumes you already have: country\_combined\_full)}
\NormalTok{country\_combined\_full }\OtherTok{\textless{}{-}}\NormalTok{ country\_combined\_full }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{inner\_join}\NormalTok{(witch\_clean, }\AttributeTok{by =} \StringTok{"country"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Error: object 'country_combined_full' not found
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 4. Run regression}
\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(anti\_imm\_rate }\SpecialCharTok{\textasciitilde{}}\NormalTok{ belief\_mean }\SpecialCharTok{+}\NormalTok{ exclusivism\_rate }\SpecialCharTok{+}\NormalTok{ witchcraft\_rate,}
            \AttributeTok{data =}\NormalTok{ country\_combined\_full)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Error in eval(mf, parent.frame()): object 'country_combined_full' not found
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Error: object 'model' not found
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{country\_belief }\OtherTok{\textless{}{-}}\NormalTok{ wvs }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{transmute}\NormalTok{(}
    \AttributeTok{country =}\NormalTok{ B\_COUNTRY\_ALPHA,}
    \AttributeTok{belief =}\NormalTok{ (}\FunctionTok{as.numeric}\NormalTok{(Q164) }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{/} \DecValTok{9}   \CommentTok{\# 👈 rescale}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(belief)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(country) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{belief\_mean =} \FunctionTok{mean}\NormalTok{(belief, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{n =} \FunctionTok{n}\NormalTok{(),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(n }\SpecialCharTok{\textgreater{}=} \DecValTok{50}\NormalTok{)}

\NormalTok{country\_combined\_full }\OtherTok{\textless{}{-}}\NormalTok{ country\_df }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{inner\_join}\NormalTok{(country\_religion\_exclusion, }\AttributeTok{by =} \StringTok{"country"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{inner\_join}\NormalTok{(country\_belief, }\AttributeTok{by =} \StringTok{"country"}\NormalTok{)}

\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(anti\_imm\_rate }\SpecialCharTok{\textasciitilde{}}\NormalTok{ belief\_mean }\SpecialCharTok{+}\NormalTok{ exclusivism\_rate,}
            \AttributeTok{data =}\NormalTok{ country\_combined\_full)}

\FunctionTok{summary}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = anti_imm_rate ~ belief_mean + exclusivism_rate, 
##     data = country_combined_full)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.21312 -0.09658 -0.03581  0.07048  0.39792 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(>|t|)    
## (Intercept)       0.19851    0.04663   4.257 7.15e-05 ***
## belief_mean      -0.16146    0.07029  -2.297    0.025 *  
## exclusivism_rate  0.30112    0.07017   4.291 6.35e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.1359 on 62 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.2295, Adjusted R-squared:  0.2047 
## F-statistic: 9.235 on 2 and 62 DF,  p-value: 0.0003086
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(modelsummary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'modelsummary' was built under R version 4.5.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{modelsummary}\NormalTok{(}
\NormalTok{  model,}
  \AttributeTok{coef\_map =} \FunctionTok{c}\NormalTok{(}
    \AttributeTok{belief\_mean =} \StringTok{"Religious belief"}\NormalTok{,}
    \AttributeTok{exclusivism\_rate =} \StringTok{"Religious exclusivism"}
\NormalTok{  ),}
  \AttributeTok{stars =} \ConstantTok{TRUE}
  
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}
\centering
\begin{talltblr}[         %% tabularray outer open
entry=none,label=none,
note{}={+ p \num{< 0.1}, * p \num{< 0.05}, ** p \num{< 0.01}, *** p \num{< 0.001}},
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]},
hline{2}={1-2}{solid, black, 0.05em},
hline{6}={1-2}{solid, black, 0.05em},
hline{1}={1-2}{solid, black, 0.08em},
hline{14}={1-2}{solid, black, 0.08em},
column{2}={}{halign=c},
column{1}={}{halign=l},
}                     %% tabularray inner close
& (1) \\
Religious belief & \num{-0.161}* \\
& (\num{0.070}) \\
Religious exclusivism & \num{0.301}*** \\
& (\num{0.070}) \\
Num.Obs. & \num{65} \\
R2 & \num{0.230} \\
R2 Adj. & \num{0.205} \\
AIC & \num{-70.0} \\
BIC & \num{-61.3} \\
Log.Lik. & \num{39.016} \\
F & \num{9.235} \\
RMSE & \num{0.13} \\
\end{talltblr}
\end{table}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(haven)}

\NormalTok{witch }\OtherTok{\textless{}{-}} \FunctionTok{read\_dta}\NormalTok{(}\StringTok{"\textasciitilde{}/Downloads/dataverse\_files/plos\_data\_country.dta"}\NormalTok{)}


\FunctionTok{names}\NormalTok{(witch)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "country"           "isocode"           "continent"        
##  [4] "witchcraft"        "abslat"            "rugged"           
##  [7] "calsuit"           "distcoast"         "religiosity"      
## [10] "kinshipsch"        "wgirl"             "wgige"            
## [13] "wgicc"             "secure"            "taxeff"           
## [16] "justsys"           "legit"             "conflocpolice"    
## [19] "confjudsys"        "confnatgov"        "schautoembed"     
## [22] "hofidv"            "hofuai"            "hofivr"           
## [25] "uzloose"           "traditionwvs"      "creativewvs"      
## [28] "riskwvs"           "chindependencewvs" "chimaginewvs"     
## [31] "crithink"          "trustinoutwvs"     "bloodfam"         
## [34] "chtolerancewvs"    "mai"               "trustgen"         
## [37] "trustnbrglp"       "trustoutwvs"       "trustbuspar"      
## [40] "fairwvs"           "impfriendswvs"     "impleisurewvs"    
## [43] "blood"             "charity"           "strangerhelp"     
## [46] "whrhappy"          "subjhealthwvs"     "whrposaffect"     
## [49] "whrnegaffect"      "controlwvs"        "whrfreechoice"    
## [52] "fatalism"          "hardwork"          "bzsg"             
## [55] "limgoodwvs"        "entrisk"           "disideas"         
## [58] "patapp"            "hindex"            "rdtogdp"          
## [61] "lngdppcppp"        "lnpovrat"          "lifexp"           
## [64] "schyears"          "hdi"               "disastexp"        
## [67] "droughtexp"        "disrichness"       "newconfreq"       
## [70] "unemprate"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(haven)}

\NormalTok{witch }\OtherTok{\textless{}{-}} \FunctionTok{read\_dta}\NormalTok{(}\StringTok{"\textasciitilde{}/Downloads/dataverse\_files/plos\_data\_country.dta"}\NormalTok{)}


\NormalTok{witch\_clean }\OtherTok{\textless{}{-}}\NormalTok{ witch }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{transmute}\NormalTok{(}
    \AttributeTok{country =}\NormalTok{ isocode,}
    \AttributeTok{witchcraft\_rate =}\NormalTok{ witchcraft}
\NormalTok{  )}

\NormalTok{country\_combined\_full }\OtherTok{\textless{}{-}}\NormalTok{ country\_combined\_full }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{inner\_join}\NormalTok{(witch\_clean, }\AttributeTok{by =} \StringTok{"country"}\NormalTok{)}

\CommentTok{\# Model 1}
\NormalTok{m1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(witchcraft\_rate }\SpecialCharTok{\textasciitilde{}}\NormalTok{ belief\_mean, }\AttributeTok{data =}\NormalTok{ country\_combined\_full)}

\CommentTok{\# Model 2}
\NormalTok{m2 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(witchcraft\_rate }\SpecialCharTok{\textasciitilde{}}\NormalTok{ exclusivism\_rate, }\AttributeTok{data =}\NormalTok{ country\_combined\_full)}

\CommentTok{\# Model 3}
\NormalTok{m3 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(witchcraft\_rate }\SpecialCharTok{\textasciitilde{}}\NormalTok{ belief\_mean }\SpecialCharTok{+}\NormalTok{ exclusivism\_rate,}
         \AttributeTok{data =}\NormalTok{ country\_combined\_full)}

\FunctionTok{modelsummary}\NormalTok{(}
  \FunctionTok{list}\NormalTok{(}\StringTok{"Belief only"} \OtherTok{=}\NormalTok{ m1,}
       \StringTok{"Exclusivism only"} \OtherTok{=}\NormalTok{ m2,}
       \StringTok{"Both"} \OtherTok{=}\NormalTok{ m3),}
  \AttributeTok{coef\_map =} \FunctionTok{c}\NormalTok{(}
    \AttributeTok{belief\_mean =} \StringTok{"Religious belief"}\NormalTok{,}
    \AttributeTok{exclusivism\_rate =} \StringTok{"Religious exclusivism"}
\NormalTok{  ),}
  \AttributeTok{statistic =} \StringTok{"(\{std.error\})"}\NormalTok{,}
  \AttributeTok{stars =} \ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{output =} \StringTok{"table2.html"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}


\end{document}
